id: I03AE8EF9
legacy_id: P002925
ocr_import_info:
  bdrc_scan_id: W2PD16796
  source: bdrc
  ocr_info:
    timestamp: '2020-03-21T23:06:47'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T09:43:14.837021+00:00'
last_modified: 2022-09-03 17:43:26.103836
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W2PD16796
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW2PD16796
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྔ་བའི་ས་མིང་།
statistics:
  ocr_word_mean_confidence_index: 0.9638070087277976
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I2PD16800:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD16800
      total_pages: 248
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2PD16800.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9638070087277976
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
