id: P002925
initial_creation_type: ocr
source_metadata:
  id: bdr:W2PD16796
  title: རྔ་བའི་ས་མིང་།
  author: ''
  volumes:
    3568219742854b429560c4dde6b3c71b:
      image_group_id: I2PD16800
      title: ''
      volume_number: 1
      total_pages: 248
